package com.salmanlaghari.pulsemusicplayerai.presentation.ui.visualizer

enum class VisualizerPreset(val displayName: String, val category: String, val description: String) {
    CIRCULAR_BARS("Circular Radial Bars", "Radial", "Bars arranged in a radial layout extending outward with simulated frequency."),
    CONCENTRIC_RINGS("Concentric Wave Rings", "Radial", "Multiple concentric wave rings expanding and pulsating on simulated beats."),
    LINEAR_BARS("Linear Glowing Bars", "Bars", "Traditional equalizer-style glowing bars standing on a bottom baseline."),
    PARTICLE_ORB("Glowing Particle Orb", "Particles", "A central glowing sphere surrounded by particles orbiting with beats."),
    STARFIELD("Retro Starfield", "Ambient", "A field of stars moving outward from the center, speed responsive to simulated audio."),
    FLUID_WAVE("Fluid Audio Wave", "Fluid", "Smooth bezier fluid wave layers morphing seamlessly across the viewport."),
    ISOMETRIC_GRID("Isometric 3D Grid", "3D", "Cubes drawn in isometric projection, heights scaling with frequency indices."),
    FLOATING_BUBBLES("Floating Bubbles", "Particles", "Floating glowing bubbles bobbing and scaling with frequency beats."),
    KALEIDOSCOPE("Kaleidoscope Ring", "Symmetric", "Symmetric geometric vector segments mirrored around a rotating origin."),
    DOUBLE_HELIX("DNA Double Helix", "Symmetric", "Two intertwined rotating waves forming a glowing double helix."),
    TUNNEL_WARP("Tunnel Warp", "3D", "Concentric rotating squares zooming outward creating a speed warp tunnel."),
    HEARTBEAT_PULSAR("Heartbeat Pulsar", "Fluid", "An ECG-style horizontal pulse wave reacting with a dynamic pulsar node."),
    FLAME_SPECTRUM("Flame Spectrum", "Bars", "Rising trails of dynamic red-to-yellow spectrum bars resembling flames."),
    MATRIX_RAIN("Matrix Digital Rain", "Ambient", "Digital rain columns falling with speed and brightness driven by audio."),
    SOUND_RIBBON("Sound Wave Ribbon", "Fluid", "A continuous smooth bezier ribbon weaving across the viewport in real-time."),
    NEON_BARS("Neon Spectrum Bars", "Bars", "Vibrant neon-tinted columns pulsing from top and bottom baselines."),
    GALAXY_RING("Galaxy Space Ring", "Radial", "A rotating ring of space particles expanding on simulated bass drops."),
    AURORA_FLOW("Aurora Flow Glow", "Ambient", "Ambient waves of organic colored glow mimicking Northern Lights."),
    FIRE_SPECTRUM("Dynamic Fire", "Ambient", "Pulsating trails of thermal fire particles rising with sound intensity."),
    WATER_WAVES("Symmetric Water Waves", "Fluid", "Concentric water ripples echoing outward with organic damping."),
    PLASMA_WAVE("Plasma Wave Fusion", "Fluid", "High-frequency plasma lines morphing with high-velocity speed."),
    FREQUENCY_LINES("Frequency Sine Lines", "Symmetric", "Clean overlaid sine-wave frequency indicator bands."),
    COLOR_BURST("Color Burst Particles", "Particles", "Explosive particle bursts expanding from click/beat center."),
    SPIRAL_GALAXY("Cosmic Spiral Galaxy", "Radial", "A gorgeous rotating multi-arm spiral galaxy of glowing cosmic dust."),
    RAINBOW_RING("Rainbow Spectrum Ring", "Radial", "A full-spectrum rainbow ring of dots pulsating radially."),
    LASER_BEAMS("Pulsating Lasers", "Ambient", "Dynamic sharp vector laser rays projecting from center corners."),
    CRYSTAL_MESH("Glowing Crystal Mesh", "3D", "Interconnected structural poly nodes forming a glowing crystal mesh."),
    SMOKE_TRAILS("Fluid Smoke Trails", "Fluid", "Translucent fluid smoke ribbons swirling slowly in 3D projection."),
    CYBER_GRID("Cybernetic Digital Grid", "3D", "A perspective grid of glowing coordinates waving with beats."),
    INFINITY_LOOP("Infinity Wave Loop", "Symmetric", "Overlaid sines drawing a rotating, pulsating infinity loop."),
    RETRO_GRID("Retro Synthwave Grid", "3D", "Retro synthwave grid lines sliding forward with audio intensity."),
    LIGHTNING_BOLT("Electrical Lightning", "Ambient", "High-voltage electrical branches arcing across the screen on beats."),
    ORBITAL_RINGS("Orbital Ring System", "Radial", "Planetary rings revolving dynamically with custom visual tilt."),
    MIRROR_SYMMETRY("Mirrored Symmetry", "Symmetric", "Left-to-right perfectly mirrored complex acoustic waves."),
    HEXAGON_MESH("Hexagonal Hive Mesh", "3D", "A structural grid of glowing hexagons pulsing individually."),
    ENERGY_SHIELD("Energy Pulse Shield", "Symmetric", "A defensive force field bubble vibrating under wave impacts."),
    DIAMOND_GLOW("Pulsating Diamond", "Symmetric", "A nested set of glowing diamonds scaling with acoustic beats."),
    METEOR_SHOWER("Meteor Rain Shower", "Ambient", "Diagonal high-speed meteor streaks flashing responsive to transients."),
    SNOWFALL("Acoustic Snowfall", "Ambient", "Delicate snowflakes falling down, drifting horizontally on beats."),
    FIREWORKS("Fireworks Burst", "Particles", "Splendid fireworks shell explosions lighting up the screen."),
    OCEAN_TIDES("Rhythmic Ocean Tides", "Fluid", "Deep vertical swells of water waves rising and falling smoothly."),
    SPECTRUM_X("Extreme Spectrum X", "Bars", "A high-intensity dual-ended spectrum cross expanding on beats."),
    ULTRA_BASS("Ultra Bass Resonator", "Radial", "A heavy bass ring that vibrates and distorts with simulated low-end."),
    AURORA_X("Cinematic Aurora X", "Ambient", "Rich, multi-layered cosmic aurora bands waving slowly."),
    GLASS_RING("Glass Specular Ring", "Radial", "A translucent glassmorphic ring refractively scaling on beats."),
    PLASMA_X("Plasma Energy Reactor", "Ambient", "An energetic circular plasma reactor with arc discharges."),
    CYBER_WAVE("Cyberpunk Digital Wave", "Fluid", "An 8-bit stepped digital waveform scanning horizontally."),
    INFINITY_BARS("Infinity Spectrum Bars", "Bars", "Overlaid vertical bars creating an infinite mirrored horizon."),
    FUTURE_PULSE("Future Audio Pulse", "Radial", "An advanced circular telemetry pulse indicator ring."),
    DIGITAL_STORM("Digital Audio Storm", "Ambient", "A storm of binary code particles flashing with audio."),
    PRISM("Prism Color Dispersion", "Symmetric", "Light refraction vectors splitting into beautiful rainbow colors."),
    QUANTUM("Quantum Particle Cloud", "Particles", "A cloud of high-velocity subatomic wave particles.")
}
